# Generated by Django 5.1.2 on 2024-11-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_01',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('password', models.CharField(max_length=64, null=True)),
                ('sex', models.CharField(max_length=64, null=True)),
                ('age', models.CharField(max_length=64, null=True)),
                ('phone', models.CharField(max_length=64, null=True)),
                ('email', models.CharField(max_length=64, null=True)),
                ('unit', models.CharField(max_length=64, null=True)),
                ('avatar', models.CharField(max_length=64, null=True)),
                ('status', models.CharField(max_length=64, null=True)),
                ('create_time', models.CharField(max_length=64, null=True)),
                ('delete_time', models.CharField(max_length=64, null=True)),
                ('update_time', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'f_user_01',
            },
        ),
    ]
