# Generated by Django 5.1.2 on 2024-11-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_01',
        ),
    ]
